#!/bin/sh

find . -type d -name '.git' | sort | while read -r line
do
    (
        cd "$line" || continue
        cd .. || continue

        repo_path="$line"
        repo_path="${repo_path%%/.git*}"
        repo_path="${repo_path##./}"
        printf '## %s\n' "$repo_path"

        printf '    %s\n' "$(du -hs . | cut -f1)"

        git status --porcelain --ignored | (grep -o '^..' || printf '==\n') | sort -r | uniq -c | sed 's/1 ==/  clean/;s/!!/ignored/;s/??/untracked/'

        for remote in $(git remote)
        do
            printf '    remote %s\n' "$remote"
            git remote show "$remote" 2>&1 | grep -oP '^[^* ].*|(?<=Fetch URL: ).+|(?<=\().+(?=\))' | sed 's/^/        /' | uniq
        done

        printf '\n'
    )
done
